services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile     
    working_dir: /srv/bot       
    env_file:
      - .env
    environment:
      BOT_MAX_TOKEN: ${BOT_MAX_TOKEN}

      BOT_BFF_BASE_URL: ${BOT_BFF_BASE_URL:-https://d5df3k4qn0v3e28jf07g.y1haggxy.apigw.yandexcloud.net/api/v1}

      BOT_PUBLIC_FRONT_URL: ${BOT_PUBLIC_FRONT_URL:-https://max-bot0.vercel.app/}
      
      BOT_POSTGRES_DSN: "postgresql+asyncpg://maxadmin:Admin1234@rc1b-e48029olq8elpa2g.mdb.yandexcloud.net:6432/app"
    command: >
      python -m app.main
    restart: unless-stopped
